public enum ModuleType
{
    NULL,
    AUTOMATIC_TURRET,
    BURST_FIRE_TURRET,
    SNIPER_TURRET,
    TESLA_COIL,
    EXPLOSIVE_SHELL_MORTAR,
    TOXIC_SHELL_MORTAR,
    DRONE_CONTACT_DAMAGE,
    DRONE_BLOCK_BULLETS,
    SHOCKWAVE_MORTAR,
    LASER_ACTIVE,
    ZAPPER,
    DEFAULT_TURRET,
    DRONE_BASICS,
    HELP_PLAYER_MOVEMENT,
    SAWBLADE_ACTIVE
}

