public enum DisplayStat
{
    SHOP_MANAGER_OVER_CHARGERS,
    SHOP_MANAGER_UNLOCKERS,
    SHOP_MANAGER_RESOURCES,
    UPGRADE_MANAGER_UPGRADE_POINTS,
    SHOP_MANAGER_CAPACITY,
    SHOP_MANAGER_FREE_PURCHASES
}
